language: node_js
node_js:
  - "8"
cache:
  yarn: true
  directories:
    - "node_modules"
addons:
  apt:
    packages:
      - xvfb
before_install:
    - yarn global add codecov
cache:
  directories:
    - "node_modules"
script:
    - yarn run lint
    - yarn run build
    - xvfb-run yarn run test:ci
after_success:
  - codecov